### ISSUE TITLE
recurse_subkeys only whole hive?

### ISSUE THREAD

**Issue by Ic1k-Git** [mkorman90/regipy#144]
Hello,
when i try to use recurse_subkeys function on particularly path instead of whole hive. Instead of getting data from part of registry I get whole hive listed with path joined in returned data. Like shown bellow:

for entry in reg.recurse_subkeys(path=r"System\ControlSet001\Services", as_json=True):
    print(entry.path)

returned data:
**System\ControlSet001\Services**\ControlSet001\Control\ACPI
**System\ControlSet001\Services**\ControlSet001\Control\AGP
**System\ControlSet001\Services**\ControlSet001\Control\AppID\CertChainStore
**System\ControlSet001\Services**\ControlSet001\Control\AppID\CertStore

**Comment by tincho9** [comment]
I'll take a look during the next weekend. It happens with every hive?

**Comment by Ic1k-Git** [comment]
I've tried for SOFTWARE, SECURITY and NTUSER and it happend every time.

**Comment by wizir6** [comment]
I also faced with this issue. @Ic1k-Git , `path` argument has not obvious name and you should not use it as subpath from start. This argument is used to save whole path from root during recursive execution because each registry node doesn't have this information.

You could use next code to achieve your goal
```
for entry in reg.recurse_subkeys(nk_record=reg_obj.root.get_key('ControlSet001\Services'), as_json=True):
    print(entry.path)
```

@tincho9 , what do you think about adding this information to comments or maybe to change argument name? 
I have also found strange behavior with `get_keys()` method. From SOFTWARE registry file
`reg.root.get_key('ODBC')` returns valid result
`reg.get_key('ODBC')` returns None when `reg.get_key('SOFTWARE\ODBC')` still returns valid object.

**Comment by tincho9** [comment]
Sorry about the confusion. 
`reg` is a `RegistryHive` object, while `reg.root` is an `NKRecord`. The `get_key` function is different in each one of them. 
The function in `RegistryHive` will resolve the path and return the key, while the `get_key` function in `NKRecord` will try to find a subkey by this name directly under the subkey. I've renamed the function in `NKRecord` to `get_subkey`. 
Hope this will solve the confusion. 

```
reg.root.get_subkey('ODBC')
reg.get_key('ODBC')
reg.get_key('SOFTWARE\ODBC')
```
These three now return the same result.

**Comment by tincho9** [comment]
I've also changed the variable named and added some documentation in the docstring. 
If this works for you, i'll make a pypi release later on today.

**Comment by tincho9** [comment]
> I've also changed the variable named and added some documentation in the docstring.
> If this works for you, i'll make a pypi release later on today.

@Ic1k-Git @wizir6 
Can I close this issue?
